### ISSUE TITLE
Single-label domain is stripped from URL

### ISSUE THREAD

**Issue by jameshfisher** [auraphp/Aura.Uri#22]
Test case:

```
<?php

require_once __DIR__ . "/vendor/autoload.php";

use Aura\Uri\Url\Factory as UrlFactory;
use Aura\Uri\PublicSuffixList;

$psl = new PublicSuffixList(require_once __DIR__ . '/vendor/aura/uri/data/public-suffix-list.php');
$url_factory = new UrlFactory($_SERVER, $psl);
$url = $url_factory->newInstance('http://localhost/');
echo $url->__toString() . "\n";
```

Expected output:

```
http://localhost/
```

Actual output:

```
http://
```

Version 1.1.1 of Aura.Uri.

**Comment by jameshfisher** [comment]
[The same issue is present in Purl, another URL manipulation library.](https://github.com/jwage/purl/issues/29)

**Comment by jameshfisher** [comment]
The error appears be a mistaken assumption in the library, rather than an accidental bug: https://github.com/auraphp/Aura.Uri/blob/develop/src/Aura/Uri/Host.php

**Comment by harikt** [comment]
if you have a fix for it. pull request welcome :) .

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/auraphp ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by jeremykendall** [comment]
@harikt @jameshfisher This is related to php-domain-parser.  I'll take a look and see what I can't work out.  Thanks for the report, @jameshfisher.

**Comment by harikt** [comment]
Thank you @jeremykendall for the heads up.

**Comment by jeremykendall** [comment]
This is fixed in php-domain-parser.  I owe you guys an integration ASAP.  I'll submit a PR as soon as I can.

**Comment by harikt** [comment]
@jeremykendall are you working on this ?

**Comment by jeremykendall** [comment]
@harikt Yes, I am.

**Comment by harikt** [comment]
@jeremykendall I am wondering what timezone are you. Is it morning or you didn't slept ?

**Comment by jeremykendall** [comment]
@harikt I'm GMT -5:00.  I'm not sleeping well lately :-/

**Comment by harikt** [comment]
ok, not too late I assume ;) . 

Around 10:30 PM.

**Comment by jeremykendall** [comment]
@harikt No, you did the math wrong.  We were chatting around 04:30 Central Daylight Time.  I'm pretty pooped.

**Comment by jeremykendall** [comment]
@harikt && @pmjones: Would you guys be willing to look over this php-domain-parser pull request: https://github.com/jeremykendall/php-domain-parser/pull/23?  It's a good idea of the changes I'll have to make here in order to resolve this issue.

I'm also planning to add support for ftp protocol (see https://github.com/jeremykendall/php-domain-parser/commit/6a8765fbeb562b3b426f090db672151f865aad82) and "schemeless" URLs (see: https://github.com/jeremykendall/php-domain-parser/blob/ec7866a625cacae846e60e905adfb9f0f3b6b9ef/library/Pdp/Uri/Url.php#L108).

If any of the changes mentioned are cause for concern or you don't want them, speak now (soon-ish) or forever hold your peace and merge my PRs :smile:

**Comment by harikt** [comment]
@jeremykendall I am not the authority. You should ping @pmjones .

**Comment by harikt** [comment]
and I am not against adding a support :+1:  . And by the way you are a member of aura. Why is it not showing on your profile ?

**Comment by pmjones** [comment]
@jeremykendall I see nothing obviously problematic with https://github.com/jeremykendall/php-domain-parser/pull/23 . The main issue is, will it be a BC break?

**Comment by jeremykendall** [comment]
@pmjones No, no BC break.  I had to touch the interface for `Pdp\Uri\Url\Host::__construct`, but I won't have to do that in `Aura\Uri\Host`.  I didn't have to change the interface anywhere in Aura.Uri, as a matter of fact.  Pretty sweet, IMHO.

**Comment by pmjones** [comment]
Ehhxcellent. Make the PR at your convenience, then.
