### ISSUE TITLE
Repo transfer is needed I guess

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Uri#3]
Hi Guys , 

As we made Aura.Uri as the official repo, but still its showing as a fork from @compwright .

I don't have any issues showing it , but there will be a feeling that this is the official repo. What I would like to do is make a repo transfer by @compwright after merging the latest one .

Probably else there can be confusion for the repo ?

**Comment by compwright** [comment]
How would I do that? Paul do you feel this is necessary?

On Wednesday, August 1, 2012, Hari K T <
reply@reply.github.com>
wrote:

**Comment by harikt** [comment]
Repo transfer seems easy.

From the admin options of the repo in github we can move.

But I feel in that case Aura.Uri may need to be remove first .

or I will contact ( I prefer @compwright itself ) github  to see whether we
can make it happen without it .

And also we can hear @pmjones

**Comment by harikt** [comment]
I did send a mail contents as follows

```
Hi Guys, 
We have a team @auraphp in github . 
One of the maintainer created a package called https://github.com/compwright/Aura.Uri/ 
We later forked and made it as official repo at https://github.com/auraphp/Aura.Uri/
How can we remove the forked from https://github.com/compwright/Aura.Uri/  to make this as official repo ?
Do we want to delete the https://github.com/auraphp/Aura.Uri/  and start a 
transfer from the repo owner @compwright or can you do the needful ?
```

**Comment by pmjones** [comment]
@compwright If you feel comfortable doing so, you may wish to delete your Aura.Uri repo, as it has been incorporated into the official Aura repo.  The only reason is an aesthetic one, so that the official repo doesn't show as a fork of something else.  (There's no need to transfer it.)  However, there's no problem with you retaining it if you like, for whatever reason.  (FYI, you are credited in that repo as a developer.) Your call dude. :-)

**Comment by harikt** [comment]
One thing is you can see the commits here

https://github.com/auraphp/Aura.Uri/commits/master

But when you look into the Contributors Graph  you are missing for I feel
you have not configure the user name or email correctly .

https://github.com/auraphp/Aura.Uri/graphs/contributors

As you can see from the commits to master itself your name is there , but
not linked to your github account .

And now the ball is in your court . We don't have any issues anyway :) .

Thank you for the hard work .

**Comment by compwright** [comment]
Well I was still planning to contribute some unit tests, wouldn't I need my
own repo to do that? My understanding was that we weren't supposed to
commit to aura master.

On Thursday, August 2, 2012, pmjones <
reply@reply.github.com>
wrote:

**Comment by harikt** [comment]
@compwright The Aura.Uri has changed from your last commit :) . It has now
tests also ( Not sure whether you mean adding more tests ).

So what I can suggest is if you are comfortable delete the repo and then
fork it from Aura.Uri .

Hope that may change , I am not sure though .

Thanks

**Comment by harikt** [comment]
aah forgot about the question of commit .

all additional stuffs you are going to do is checkout develop to new
branch  and give a PR to the develop branch of Aura.

That means you don't commit to your develop or master branch .

Have a look into the article
http://auraphp.github.com/2012/07/13/contributing-to-aura-project/ .

I can try to help if needed via irc or via tweet or shoot a mail what ever
you are comfortable . I prefer mail or irc for tweet is short .

**Comment by pmjones** [comment]
@compwright: I completed the unit tests some time ago; they are at 100% coverage. :-)

**Comment by harikt** [comment]
:thumbsup:

**Comment by compwright** [comment]
OK, great. It has been deleted.

On Thu, Aug 2, 2012 at 9:45 AM, pmjones <
reply@reply.github.com

**Comment by harikt** [comment]
oh cool and it became the fork of my repo :P . Now I have deleted mine and forked again . Great! , so Aura.Uri now becomes official.
