### ISSUE TITLE
Aura.Uri should not require "aura/installer-default": "*"

### ISSUE THREAD

**Issue by calvinfroedge** [auraphp/Aura.Uri#8]
Composer install chokes:

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for aura/uri dev-master -> satisfiable by aura/uri dev-master.
    - aura/uri dev-master requires aura/installer-default \* -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by harikt** [comment]
I didn't get the error . It seems you have not kept the minimum-stability
to dev . This is my composer.json

{
    "minimum-stability": "dev",
    "require": {
        "aura/uri":"dev-master"
    }
}

*Hari K T
*M: +91-9388758821 | W: http://harikt.com/blog

**Comment by calvinfroedge** [comment]
Got ya.  Thanks!  But...if the installer is not required to use the uri class should the installer be required in composer.json?

**Comment by harikt** [comment]
@calvinfroedge so about the installer , its a big story :) . But in short its needed for composer for we want to install all aura packages in package folder when it comes to framework . So ie it :) .

**Comment by harikt** [comment]
This issue can be closed @pmjones . I don't have access :-1:  ;) .
