### ISSUE TITLE
Empty elements in $urlFactoryInstance->path

### ISSUE THREAD

**Issue by calvinfroedge** [auraphp/Aura.Uri#9]
Uri\Url\Factory instance for site.dev/foo/bar yields the following path property:

array(4) { [0]=> string(0) "" [1]=> string(3) "foo" [2]=> string(3) "bar" [3]=> string(0) "" }

Is there a reason for the two empty array elements?  My expectation would be to receive this:

array(4) { [0]=>  string(3) "foo" [1]=> string(3) "bar" }

**Comment by calvinfroedge** [comment]
Btw if you agree with this I can make the change...

**Comment by harikt** [comment]
@calvinfroedge I feel you are correct. But I will wait for @pmjones . If  its an easy one you can work on creating a branch from develop and sending a PR to develop branch itself . 

Thank you for the bugs and welcome tests :+1:  .

**Comment by pmjones** [comment]
This should be fixed. Let me know if it is not.
